### ISSUE TITLE
Valeurs de l'axe Y

### ISSUE THREAD

**Issue by ptstream** [vivien000/vaccine-stats#1]
Bonjour,
Bravo pour votre travail qui met en forme les données de la Drees.
Toutefois une petite chose me chiffonne. Si je ne fais pas d'erreur, le calcul des valeurs est essentiellement basé sur l'effectif (par exemple 1e6 * x.hc_pcr / x.effectif). Vous considérez donc que les données sont des nombres de personnes (ce qui parait évident pour les effectifs).  Dans ce cas, je ne comprend pas pourquoi la Drees produit des nombre avec partie décimale et non des nombres entiers. Cela voudrait dire que ces nombres réels sont le résultat de calculs. Sur leur site, je ne trouves pas comment ces valeurs sont calculés.
Si le considère que les valeurs du 12/12/2021 étaient particulièrement folkloriques. Je reste dubitatif concernant la validité de ce type de graphiques (le travaille semble sérieux par contre il se base sur des données qui sont très étranges).
Bien cordialement

**Comment by vivien000** [comment]
Bonjour Patrice. Merci pour votre retour.

J'avais aussi vu ça en examinant les données de la DREES : les valeurs d'effectif sont entières mais les nombres de cas sont parfois des nombres décimaux.

Je ne sais pas d'où cela vient mais je ne pense pas que les données soient suspectes pour autant.

On peut imaginer plusieurs mécanismes qui pourraient conduire à des valeurs non entières. Par exemple :
- les données ne sont pas remontées quotidiennement par certains professionnels de santé et la DREES applique un traitement pour recontruire des séries journalières. Par exemple, pour un hôpital donné, si 20 cas sont remontés pour 3 jours consécutifs, on considère qu'il y a 6,67 cas chacun de ces 3 jours.
- les données remontées sur les cas contiennent les années de naissance des patients mais pas les dates précises. Ainsi, si un cas concernant une personne née en 1961 est remonté le 1er juillet 2021, on ne peut pas savoir s'il faut le ranger dans la catégorie 40-59 ans ou la catégorie 60-79 ans. Dans ce cas, la DREES pourrait par convention considérer qu'il y a 0.5 cas dans chacune des 2 catégories.
- ...

Si vous voulez creuser ce point, vous pourriez contacter la DREES (https://drees.solidarites-sante.gouv.fr/contact). Si vous faites cette démarche et si vous avez une réponse de la DREES, je serais volontiers preneur de cette solution.

**Comment by ptstream** [comment]
Bonjour Vivien,
Un grand merci pour la réponse à mes questions.
Ce que vous décrivez est toute à fait plausible.  
En fait, mon doute venais des données 12/12/2021 qui étaient particulièrement folkloriques. Je les ai contacté et des corrections ont été apportées depuis. Toutefois je ne sais pas si j'y suis pour quelque chose car ils ne répondent jamais.
Bien entendu, je vous laisse le soin de clore ce fil. 
Bien cordialement
